config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/dashboard', to: 'dashboard#dashboard', as: 'dashboard'
  devise_for :user, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :animais
  resources :donos

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  # devise_scope :user do
  #   root 'devise/sessions#new'
  # end

  root to: 'dashboard#dashboard'
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
      user ||= User.new # guest user (not logged in)
      if user
        can :manage, :all
      end
  end
end

app/models/animal.rb
class Animal < ApplicationRecord
  belongs_to :dono

  has_one_attached :foto

  enum status: {curado: 0, internado: 1, observacao: 2}
  attribute :status, :integer
  enum sexo: {macho: 0, femea: 1}

  validates :nome, length: { minimum: 1, maximum: 255 }
  validates :idade, numericality: { only_integer: true,
                                    less_than_or_equal_to: 999 }
  validates :doenca, length: { minimum: 1, maximum: 255 }
  validates :medicamento, length: { minimum: 1, maximum: 255 }

  ransacker :status do |parent|
    parent.table[:status]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dono.rb
class Dono < ApplicationRecord
  has_many :animais, dependent: :restrict_with_error

  validates :nome, length: { minimum: 1, maximum: 255 }
  validates :idade, numericality: { only_integer: true,
                                    less_than_or_equal_to: 999 }
  validates :telefone, length: { minimum: 1, maximum: 255 }
  validates :cep, length: { minimum: 1, maximum: 255 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/animais_controller.rb
class AnimaisController < ApplicationController
  before_action :set_animal, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /animais
  # GET /animais.json
  def index
    @q = Animal.ransack(params[:q])
    @animais = @q.result(distinct: true)
  end

  # GET /animais/1
  # GET /animais/1.json
  def show
  end

  # GET /animais/new
  def new
    @animal = Animal.new
  end

  # GET /animais/1/edit
  def edit
  end

  # POST /animais
  # POST /animais.json
  def create
    @animal = Animal.new(animal_params)

    respond_to do |format|
      if @animal.save
        format.html { redirect_to @animal, notice: 'Animal was successfully created.' }
        format.json { render :show, status: :created, location: @animal }
      else
        format.html { render :new }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /animais/1
  # PATCH/PUT /animais/1.json
  def update
    respond_to do |format|
      if @animal.update(animal_params)
        format.html { redirect_to @animal, notice: 'Animal was successfully updated.' }
        format.json { render :show, status: :ok, location: @animal }
      else
        format.html { render :edit }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animais/1
  # DELETE /animais/1.json
  def destroy
    @animal.destroy
    respond_to do |format|
      format.html { redirect_to animais_url, notice: 'Animal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_animal
      @animal = Animal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def animal_params
      params.require(:animal).permit(:nome, :idade, :sexo, :status, :foto, :doenca, :medicamento, :horario_medicamento_incio, :horario_medicamento_fim, :dono_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to '/', :alert => exception.message
  end

  protect_from_forgery with: :exception
  before_action :authenticate_user!
  include DeviseWhitelist


end

app/controllers/concerns/devise_whitelist.rb
module DeviseWhitelist
  extend ActiveSupport::Concern

  included do
    before_action :configure_permitted_parameters, if: :devise_controller?
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:name])
    devise_parameter_sanitizer.permit(:account_update, keys:[:name])
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
end

app/controllers/donos_controller.rb
class DonosController < ApplicationController
  before_action :set_dono, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /donos
  # GET /donos.json
  def index
    @donos = Dono.all.order("id DESC")
  end

  # GET /donos/1
  # GET /donos/1.json
  def show
  end

  # GET /donos/new
  def new
    @dono = Dono.new
  end

  # GET /donos/1/edit
  def edit
  end

  # POST /donos
  # POST /donos.json
  def create
    @dono = Dono.new(dono_params)

    respond_to do |format|
      if @dono.save
        format.html { redirect_to @dono, notice: 'Dono was successfully created.' }
        format.json { render :show, status: :created, location: @dono }
      else
        format.html { render :new }
        format.json { render json: @dono.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /donos/1
  # PATCH/PUT /donos/1.json
  def update
    respond_to do |format|
      if @dono.update(dono_params)
        format.html { redirect_to @dono, notice: 'Dono was successfully updated.' }
        format.json { render :show, status: :ok, location: @dono }
      else
        format.html { render :edit }
        format.json { render json: @dono.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donos/1
  # DELETE /donos/1.json
  def destroy
    @dono.destroy
    respond_to do |format|
      if @dono.destroy
        format.html { redirect_to donos_url, notice: 'Dono was successfully destroyed.' }
        format.json { head :no_content }
      else
        format.html { redirect_to donos_url, notice: 'Impossível deletar dono com animal associado' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dono
      @dono = Dono.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dono_params
      params.require(:dono).permit(:nome, :idade, :cep, :complemento, :rua, :bairro, :numero_casa, :telefone, :email)
    end
end

app/helpers/animais_helper.rb
module AnimaisHelper
  def image_generator(height:, width:)
    "http://placehold.it/#{height}x#{width}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/donos_helper.rb
module DonosHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sidebar_helper.rb
module SidebarHelper
  def nav_dono
    [
      {
        url: donos_path,
        title: 'Todos os donos'
      },
      {
        url: new_dono_path,
        title: 'Adicionar dono'
      }
    ]
  end

  def nav_animal
      [
        {
          url: animais_path,
          title: 'Todos os animais'
        },
        {
          url: new_animal_path,
          title: 'Adicionar Animal'
        }
      ]
      #TODO TERMINAR O NAVBAR
    end

  #Navegação do dono
  def nav_helper_dono style, tag_type
    nav_links =  ''

    nav_dono.each do |item|
      nav_links << "<#{tag_type}><a href='#{item[:url]}' class='#{style} #{active? item[:url]}'>#{item[:title]}</a></#{tag_type}>"
    end

    nav_links.html_safe
  end


  #Navegação do animal
  def nav_helper_animal style, tag_type
    nav_links =  ''

    nav_animal.each do |item|
      nav_links << "<#{tag_type}><a href='#{item[:url]}' class='#{style} #{active? item[:url]}'>#{item[:title]}</a></#{tag_type}>"
    end

    nav_links.html_safe
  end


  def active? path
    "active" if current_page? path
  end
end

app/views/animais/_animal.html.erb
<div class="col-md-4 ">
  <div class="card mb-4 shadow-sm">
    <% if animal.foto.attached? %>
      <%= image_tag animal.foto, width: "100%" %>
    <% else %>
      <%= image_tag (image_generator(height: '350', width: '200')) %>
    <% end %>
    <div class="card-body">
      <p class="card-text"><%= link_to animal.nome, animal %></p>
      <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group">
          <td><%= link_to 'Edit', edit_animal_path(animal), class: "btn btn-sm btn-outline-secondary" %></td>
          <td><%= link_to 'Destroy', animal, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-outline-secondary" %></td>
        </div>
        <small class="text-muted"><%= distance_of_time_in_words(animal.created_at, Time.now) %></small>
      </div>
    </div>
  </div>
</div>

app/views/animais/_form.html.erb
<%= form_with(model: @animal, local: true) do |form| %>
  <% if @animal.errors.any? %>
      <% @animal.errors.full_messages.each do |message| %>
      <div class="alert alert-danger" role="alert">
        <li><%= message %></li>
      </div>
    <% end %>
  <% end %>

  <div class="container">
    <div class="row">

      <div class="col-md-6 ">
        <div class="form-group">
          <%= form.text_field :nome, class: 'form-control', placeholder: 'Nome' %>
        </div>

        <div class="form-group">
          <%= form.number_field :idade, class: 'form-control', placeholder: 'Idade' %>
        </div>

        <div class="form-group">
          <%= form.collection_select :sexo,
          Animal.sexos.keys.map{|s| [s, s.capitalize]},
          :first, :last, {include_blank: 'Sexo'},
          {class: 'form-control'}%>
        </div>

        <div class="form-group">
        <%= form.collection_select :status,
            Animal.statuses.keys.map{|s| [s, s.capitalize]},
            :first, :last, {include_blank: "Selecione o status"},
            {class: 'form-control'} %>
        </div>



        <div class="form-group">
          <%= form.text_field :raca, class: 'form-control', placeholder: 'Raça' %>
        </div>

        <label class="btn btn-primary">
            Adicionar foto <%= form.file_field :foto, class: 'form-control', style: 'display:none;' %>
        </label>
      </div>

      <div class="col-md-6">
        <div class="form-group">
          <%= form.text_field :doenca, class: 'form-control', placeholder: 'Doença' %>
        </div>

        <div class="form-group">
          <%= form.text_field :medicamento, class: 'form-control', placeholder: 'Medicamento' %>
        </div>

        <div class="form-group">
          <%= form.label :horario_medicamento_incio %>
          <%= form.time_select :horario_medicamento_incio, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :horario_medicamento_fim %>
          <%= form.time_select :horario_medicamento_fim, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.collection_select :dono_id, Dono.all, :id, :nome,
          {include_blank: "Selecione o dono"},
          {class: "form-control"}%>
        </div>
      </div>

    </div>
  </div>

  <div class="form-group">
    <%= form.submit 'Cadastrar', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/animais/edit.html.erb
<main class="app-content">
  <div class="app-title">
    <h1>Editing Animal</h1>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="tile">

    <%= render 'form', animal: @animal %>

    <%= link_to 'Show', @animal %> |
    <%= link_to 'Back', animais_path %>
      </div>
    </div>
  </div>
  
</main>

app/views/animais/index.html.erb
<main class="app-content">
  <div class="app-title">
    <h1>Animais</h1>

    <%= render 'shared/filtro' %>

  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="tile">
        <p id="notice"><%= notice %></p>
        <div class="album text-muted">
          <div class="container">
            <div class="row">
              <%= render partial: 'animal', collection: @animais %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/animais/new.html.erb
<main class="app-content">
  <div class="app-title">
    <h1> New Animal </h1>

  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="tile">

          <%= render 'form', animal: @animal %>

          <%= link_to 'Back', animais_path %>
        </div>
      </div>
    </div>
</main>

app/views/animais/show.html.erb
<main class="app-content">
  <div class="row">
    <div class="col-md-12">
      <div class="tile">
        <p id="notice"><%= notice %></p>

          <div class="container animal-container">
            <div class="row">
              <div class="col-sm-12 col-md-12 col-lg-8 col-xl-7">
                <% if @animal.foto.attached? %>
                  <%= image_tag @animal.foto, width: "100%" %>
                <% else %>
                  <%= image_tag (image_generator(height: '600', width: '400')) %>
                <% end %>
              </div>

              <div class="col-sm-12 col-md-12 col-lg-4 col-xl-5">
                <p>
                  <strong>Nome:</strong>
                  <%= @animal.nome %>
                </p>

                <p>
                  <strong>Idade:</strong>
                  <%= @animal.idade %>
                </p>

                <p>
                  <strong>Sexo:</strong>
                  <%= @animal.sexo %>
                </p>

                <p>
                  <strong>Status:</strong>
                  <%= @animal.status %>
                </p>

                <p>
                  <strong>Doenca:</strong>
                  <%= @animal.doenca %>
                </p>

                <p>
                  <strong>Medicamento:</strong>
                  <%= @animal.medicamento %>
                </p>

                <p>
                  <strong>Horario medicamento incio:</strong>
                  <%= @animal.horario_medicamento_incio %>
                </p>

                <p>
                  <strong>Horario medicamento fim:</strong>
                  <%= @animal.horario_medicamento_fim %>
                </p>

                <p>
                  <strong>Dono:</strong>
                  <%= link_to @animal.dono.nome, dono_path(@animal.dono) %>
                </p>
              </div>
            </div>
          </div>


        <%= link_to 'Edit', edit_animal_path(@animal) %> |
        <%= link_to 'Back', animais_path %> |
        <%= link_to 'Adicionar animal', new_animal_path %>

      </div>
    </div>
  </div>
</main>

app/views/dashboard/_dashboard.html.erb
<div class="row">
        <div class="col-md-6 col-lg-3">
          <div class="widget-small danger coloured-icon"><i class="icon fa"><%= fa_icon 'paw' %></i>
            <div class="info">
              <h4>Todos os Animais</h4>
              <p><b>9</b></p>
            </div>
          </div>
        </div>
        <div class="col-md-6 col-lg-3">
          <div class="widget-small primary coloured-icon"><i class="icon fa"><%= fa_icon 'heartbeat'%></i>
            <div class="info">
              <h4>Animais Internados</h4>
              <p><b>3</b></p>
            </div>
          </div>
        </div>
        <div class="col-md-6 col-lg-3">
          <div class="widget-small info coloured-icon"><i class="icon fa"><%= fa_icon 'eye' %></i>
            <div class="info">
              <h4>Animais em Observação</h4>
              <p><b>3</b></p>
            </div>
          </div>
        </div>
        <div class="col-md-6 col-lg-3">
          <div class="widget-small warning coloured-icon"><i class="icon fa"><%= fa_icon 'heart'%></i>
            <div class="info">
              <h4>Animais Curados</h4>
              <p><b>3</b></p>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <div class="tile">
            <h3 class="tile-title">Monthly Sales</h3>
            <div class="embed-responsive embed-responsive-16by9">
              <canvas class="embed-responsive-item" id="lineChartDemo"></canvas>
            </div>
          </div>
        </div>
        <div class="col-md-6">
          <div class="tile">
            <h3 class="tile-title">Monthly Sales</h3>
            <div class="embed-responsive embed-responsive-16by9">
              <canvas class="embed-responsive-item" id="lineChartDemo"></canvas>
            </div>
          </div>
        </div>
        <div class="col-md-6">
          <div class="tile">
            <h3 class="tile-title">Monthly Sales</h3>
            <div class="embed-responsive embed-responsive-16by9">
              <canvas class="embed-responsive-item" id="lineChartDemo"></canvas>
            </div>
          </div>
        </div>
        <div class="col-md-6">
          <div class="tile">
            <h3 class="tile-title">Support Requests</h3>
            <div class="embed-responsive embed-responsive-16by9">
              <canvas class="embed-responsive-item" id="pieChartDemo"></canvas>
            </div>
          </div>
        </div>
      </div>

app/views/dashboard/dashboard.html.erb
<main class="app-content">
  <div class="app-title">
    <h1>Painel de controle</h1>
  </div>

  <div class="row">
    <div class="col-md-12">
      
        <%= render 'dashboard' %>

    </div>
  </div>
</main>

app/views/donos/_dono.html.erb
  <tbody id="table">
    <tr>
    <th><%= link_to dono.nome, dono %></th>
    <th><%= dono.telefone %></th>
    <th><%= dono.email %></th>

    <th class="text-right">


      <%= link_to edit_dono_path(dono), class: 'btn btn-primary' do %>
        <%= fa_icon 'edit', style: "font-size:23px" %>
      <% end %>

      <%= link_to dono, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' do %>
        <%= fa_icon 'trash', style: "font-size:23px" %>
      <% end %>
    </th>


  </tr>
  </tbody>

app/views/donos/_form.html.erb
<%= form_with(model: dono, local: true) do |form| %>
<% if @dono.errors.any? %>
    <% @dono.errors.full_messages.each do |message| %>
    <div class="alert alert-danger" role="alert">
      <%= message %>
    </div>
    <% end %>
<% end %>
<div class="container">
  <div class="row">
    
    <div class="col-md-6">
      <div class="form-group">
        <%= form.text_field :nome, class: 'form-control', placeholder: "Nome" %>
      </div>

      <div class="form-group">
        <%= form.number_field :idade, class: 'form-control', placeholder: "Idade" %>
      </div>


      <div class="form-group">
        <%= form.text_field :telefone, class: 'form-control', placeholder: "Telefone para contato" %>
      </div>

      <div class="form-group">
        <%= form.text_field :email, class: 'form-control', placeholder: "Email" %>
      </div>
    </div>




    <div class="col-md-6">
      <div class="form-group">
        <%= form.text_field :cep, class: 'form-control', placeholder: "Cep" %>
      </div>


      <div class="form-group">
        <%= form.text_field :rua, class: 'form-control', placeholder: "Rua" %>
      </div>

      <div class="form-group">
        <%= form.text_field :bairro, class: 'form-control', placeholder: "Bairro" %>
      </div>

      <div class="form-group">
        <%= form.text_field :complemento, class: 'form-control', placeholder: "Complemento" %>
      </div>

      <div class="form-group">
        <%= form.number_field :numero_casa, class: 'form-control', placeholder: "Numero da casa"%>
      </div>
    </div>

  </div>
</div>

  <div class="actions">
    <%= form.submit "Cadastrar", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/donos/edit.html.erb
<main class="app-content">
  <div class="app-title">
    <h1>Editing Dono</h1>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="tile">
        
        <%= render 'form', dono: @dono %>

        <%= link_to 'Show', @dono %> |
        <%= link_to 'Back', donos_path %>

      </div>
    </div>
  </div>
</main>

app/views/donos/index.html.erb
<main class="app-content">
  <div class="app-title">
    <h1>Donos</h1>

    <div class="float-right">
      <input class="app-search__input" id="myInput" type="text" placeholder="Digite para pesqusiar...">
    </div>
  </div>

  <!--fazer search para dono -->
  <div class="row">
    <div class="col-md-12">
      <div class="tile">
        <p id="notice"><%= notice %></p>



        <table class="table table-hover">
          <thead>
            <tr class="text-left">
              <th><h5>Nome</h5></th>
              <th><h5>Telefone</h5></th>
              <th><h5>Email</h5></th>
              <th></th>
            </tr>
          </thead>

          <%=  render partial: 'dono', collection: @donos %>
        </table>

      </div>
    </div>
  </div>

</main>

app/views/donos/new.html.erb
<main class="app-content">
  <div class="app-title">
    <h1>New Dono</h1>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="tile">

      <%= render 'form', dono: @dono %>

      <%= link_to 'Back', donos_path %>

      </div>
    </div>
  </div>
</main>

app/views/donos/show.html.erb
<main class="app-content">
  <div class="row">
    <div class="col-md-12">
      <div class="tile">
        <p id="notice"><%= notice %></p>
        <div class="row">
          <div class="col-md-6">
            <p>
              <strong>Nome:</strong>
              <%= @dono.nome %>
            </p>

            <p>
              <strong>Idade:</strong>
              <%= @dono.idade %>
            </p>

            <p>
              <strong>Telefone:</strong>
              <%= @dono.telefone %>
            </p>
            <p>
              <strong>Email:</strong>
              <%= @dono.email %>
            </p>
          </div>

          <div class="col-md-6">
            <p>
              <strong>Rua:</strong>
              <%= @dono.rua %>
            </p>

            <p>
              <strong>Bairro:</strong>
              <%= @dono.bairro %>
            </p>

            <p>
              <strong>Numero casa:</strong>
              <%= @dono.numero_casa %>
            </p>

            <p>
              <strong>Cep:</strong>
              <%= @dono.cep %>
            </p>

            <p>
              <strong>Complemento:</strong>
              <%= @dono.complemento %>
            </p>

          </div>

          <p>
            <strong>Animal:</strong>
            <% @dono.animais.each do |animal| %>
              <%= link_to animal.nome, animal %>
            <% end %>
          </p>
        </div>
        <%= link_to 'Edit', edit_dono_path(@dono) %> |
        <%= link_to 'Back', donos_path %> |
        <%= link_to 'Adicionar dono', new_dono_path %>
      </div>
    </div>
  </div>
</main>

app/views/shared/_filtro.html.erb
<%# terminar as colunas do filtro
%>


<%= search_form_for @q do |f| %>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.collection_select :status_eq,
        Animal.statuses.keys.map{|s| [s, s.capitalize]},
        :first, :last, {include_blank: "Todos os status"},
        {class: 'form-control'} %>
      </div>
    </div>

    <div class="col-md-6">
      <div class="form-group">
        <%= f.collection_select :dono_id_eq, Dono.all, :id, :nome,
        {include_blank: "Todos os donos"},
        {class: "form-control"}%>
      </div>

      <div class="text-right">
        <%= button_tag class: 'btn btn-outline-secondary' do %>
        <span aria-hidden="true">
            <i><%= fa_icon 'search' %></i>
        </span> Filtrar
        <% end %>
      </div>
    </div>

  </div>
<% end %>

app/views/shared/_navbar.html.erb
<header class="app-header">
    <a class="app-header__logo" href="#">
      <b>
        Control
      </b>
        Vet
    </a>
    <!-- Sidebar toggle button-->
    <a class="app-sidebar__toggle" href="#" data-toggle="sidebar" aria-label="Hide Sidebar"></a>

    <!-- Navbar Right Menu-->

    <ul class="app-nav">
      <li class="dropdown"><a class="app-nav__item" href="#" data-toggle="dropdown" aria-label="Open Profile Menu"><i class="fa fa-user fa-lg"></i></a>
        <ul class="dropdown-menu settings-menu dropdown-menu-right">
          <%= link_to destroy_user_session_path, method: :delete do %>
            <li class="dropdown-item"><i class="app-menu__icon"><%= fa_icon 'sign-out fa-lg' %></i> Logout</li>
          <% end %>
        </ul>
      </li>
    </ul>



</header>

app/views/shared/_sidebar.html.erb
<!-- Sidebar menu-->
<div class="app-sidebar__overlay" data-toggle="sidebar"></div>
<aside class="app-sidebar">
    <div class="app-sidebar__user"><img class="app-sidebar__user-avatar"
            src="https://s3.amazonaws.com/uifaces/faces/twitter/jsa/48.jpg" alt="User Image">
        <div>
            <p class="app-sidebar__user-name">Pedro</p>
            <p class="app-sidebar__user-designation">Ceobaniuc</p>
        </div>
    </div>
    <ul class="app-menu">
          <li>
            <%= link_to dashboard_path, class: "app-menu__item #{active?(dashboard_path)}" do %>
              <i class="app-menu__icon fa"><%= fa_icon 'dashboard'%></i>
              <span class="app-menu__label">
                Painel de controle
              </span>
            <% end %>
          </li>


        <li class="treeview"><a class="app-menu__item" href="#" data-toggle="treeview"><i class="app-menu__icon fa"><%= fa_icon 'user' %></i>
          <span class="app-menu__label">
            Dono
          </span><i class="treeview-indicator fa fa-angle-right"></i></a>
          <ul class="treeview-menu">
            <%= nav_helper_dono 'treeview-item', 'span' %>
          </ul>
        </li>

        <li class="treeview"><a class="app-menu__item" href="#" data-toggle="treeview"><i class="app-menu__icon fa"><%= fa_icon 'paw' %></i>
          <span class="app-menu__label">
            Animais
          </span><i class="treeview-indicator fa fa-angle-right"></i></a>
          <ul class="treeview-menu">
            <%= nav_helper_animal 'treeview-item', 'span' %>
          </ul>
        </li>

    </ul>

<!--
    <li><a class="app-menu__item" href="charts.html"><i class="app-menu__icon fa fa-pie-chart"></i><span
                class="app-menu__label">Charts</span></a></li>
    <li class="treeview"><a class="app-menu__item" href="#" data-toggle="treeview"><i
                class="app-menu__icon fa fa-edit"></i><span class="app-menu__label">Forms</span><i
                class="treeview-indicator fa fa-angle-right"></i></a>
        <ul class="treeview-menu">
            <li><a class="treeview-item" href="form-components.html"><i class="icon fa fa-circle-o"></i> Form
                    Components</a></li>
            <li><a class="treeview-item" href="form-custom.html"><i class="icon fa fa-circle-o"></i> Custom
                    Components</a>
            </li>
            <li><a class="treeview-item" href="form-samples.html"><i class="icon fa fa-circle-o"></i> Form Samples</a>
            </li>
            <li><a class="treeview-item" href="form-notifications.html"><i class="icon fa fa-circle-o"></i> Form
                    Notifications</a></li>
        </ul>
    </li>
    <li class="treeview"><a class="app-menu__item" href="#" data-toggle="treeview"><i
                class="app-menu__icon fa fa-th-list"></i><span class="app-menu__label">Tables</span><i
                class="treeview-indicator fa fa-angle-right"></i></a>
        <ul class="treeview-menu">
            <li><a class="treeview-item" href="table-basic.html"><i class="icon fa fa-circle-o"></i> Basic Tables</a>
            </li>
            <li><a class="treeview-item" href="table-data-table.html"><i class="icon fa fa-circle-o"></i> Data
                    Tables</a>
            </li>
        </ul>
    </li>
    <li class="treeview"><a class="app-menu__item" href="#" data-toggle="treeview"><i
                class="app-menu__icon fa fa-file-text"></i><span class="app-menu__label">Pages</span><i
                class="treeview-indicator fa fa-angle-right"></i></a>
        <ul class="treeview-menu">
            <li><a class="treeview-item active" href="blank-page.html"><i class="icon fa fa-circle-o"></i> Blank
                    Page</a>
            </li>
            <li><a class="treeview-item" href="page-login.html"><i class="icon fa fa-circle-o"></i> Login Page</a></li>
            <li><a class="treeview-item" href="page-lockscreen.html"><i class="icon fa fa-circle-o"></i> Lockscreen
                    Page</a></li>
            <li><a class="treeview-item" href="page-user.html"><i class="icon fa fa-circle-o"></i> User Page</a></li>
            <li><a class="treeview-item" href="page-invoice.html"><i class="icon fa fa-circle-o"></i> Invoice Page</a>
            </li>
            <li><a class="treeview-item" href="page-calendar.html"><i class="icon fa fa-circle-o"></i> Calendar Page</a>
            </li>
            <li><a class="treeview-item" href="page-mailbox.html"><i class="icon fa fa-circle-o"></i> Mailbox</a></li>
            <li><a class="treeview-item" href="page-error.html"><i class="icon fa fa-circle-o"></i> Error Page</a></li>
        </ul>
    </li> -->
</aside>